### ISSUE TITLE
[BUG] Doc. page ArrayType Get Accessor does not link back to ArrayType Overview

### ISSUE THREAD

**Issue by FlameHorizon** [Senipah/VBA-DynamicArray#13]
**Describe the bug**
User is not able to go back to [ArrayType Overview](https://senipah.github.io/VBA-Better-Array/api/properties/array_type/ArrayType.html) from [ArrayType Get Accessor](https://senipah.github.io/VBA-Better-Array/api/properties/array_type/arrayType_getter.html) using [Back to ArrayType overview](https://senipah.github.io/VBA-Better-Array/api/properties/array_types/ArrayType) hyperlink.

**To Reproduce**
1. Go to [ArrayType Get Accessor](https://senipah.github.io/VBA-Better-Array/api/properties/array_type/arrayType_getter.html) page.
2. Click [Back to ArrayType overview](https://senipah.github.io/VBA-Better-Array/api/properties/array_types/ArrayType) hyperlink
3. See error

**Expected behavior**
User should see [ArrayType](https://senipah.github.io/VBA-Better-Array/api/properties/array_types/ArrayType) page.

**Screenshots**
_Caption: click Back to ArrayType overview hyperlink_
![image](https://user-images.githubusercontent.com/23423558/113437769-8e5b2b00-93e7-11eb-8b2d-f1d64946d932.png)

_Caption: missing page_
![image](https://user-images.githubusercontent.com/23423558/113437846-ae8aea00-93e7-11eb-8cef-4b1a977ee27a.png)

**Additional info**

The same error does appear when if you press _ArrayTypes Enumeration_ and _ArrayTypes Enumeration_ hyperlinks.

**Comment by Senipah** [comment]
Thanks very much for letting me know about this @FlameHorizon. Links should now be fixed.
