### ISSUE TITLE
Last item Shift gives Length 1

### ISSUE THREAD

**Issue by JohnGurin** [Senipah/VBA-DynamicArray#15]
```vba
Dim ba As New BetterArray
Debug.Print ba.Length '0

ba.Push 1, 2
Debug.Print ba.Length '2

ba.Shift
Debug.Print ba.Length '1

ba.Shift
Debug.Print ba.Length '1
```
Windows 10 x64
MS Excel 2016
BetterArray v1.7.4

**Comment by Senipah** [comment]
Hi @JohnGurin,

Thanks very much for your bug report. Apologies for the inconvenience. I have been able to reproduce your issue and have shipped a fix in [v1.7.5](https://github.com/Senipah/VBA-Better-Array/releases/tag/v1.7.5).

Thanks for using BetterArray and if you have any further issues or questions please let me know.
