### ISSUE TITLE
Remove method it doesn't remove the only element of a 1 length array

### ISSUE THREAD

**Issue by kennyk4silva** [Senipah/VBA-DynamicArray#17]
**Remove method it doesn't remove the only element of a 1 length array**
I made a script that stores various string elements in a BetterArray object and then with a For...Next structure if a certain condition is met it removes one specific element of the array with the **.Remove(Index)** method. The problem is when the BetterArray object remains **with 1 element** and I want to remove it because the mentioned condition is met again at that point. BetterArray.Remove(0) simply returns the same BetterArray with one element.

**To Reproduce**

1. Simply run the following Sub procedure:
`Sub BetterArrayTest()`
`     Dim BA As New BetterArray`
`     BA.Items = Array("Hello")`
`     BA.Remove 0`
`     Debug.Print BA.ToString`
`End Sub`

2. See the result in the Inmediate Window (see screenshot). It doesn't remove the "Hello" element.

**Expected behavior**
If a BetterArray object has one element (Lenght = 1), then the syntax BetterArray.Remove(0) really remove that element.

**Screenshots**
![image](https://user-images.githubusercontent.com/28848187/131201053-7a30bc80-87b3-4007-b64f-f9c7ea3f9a35.png)

**Operating System:**
 - Windows 7 64 bits

**Host Application:**
 - MS Excel

**Additional context**
The problem is only when the BetterArray object has one element. If it has more than one element the .Remove(0) method effectively removes the first element of the array.

**Comment by Senipah** [comment]
Hi @kennyk4silva,

Thank you so much for letting me know about this! Issue should now be fixed and is available in the latest release [(v1.7.6)](https://github.com/Senipah/VBA-Better-Array/releases/tag/v1.7.6)

Thanks for using BetterArray and please let me know if you have any other issues.

**Comment by kennyk4silva** [comment]
Hi @Senipah, thank you so much for your great effort making that excellent class. I'm using it a lot processing txt files and arrays in a fast and effective way. I will let you know if I found another issue. Greetings from Venezuela.
