### ISSUE TITLE
Filter 2d arrays

### ISSUE THREAD

**Issue by mehrlander** [Senipah/VBA-DynamicArray#19]
Hi, I have been interested to explore the features of Better Array.  It seems to offer some really convenient and powerful capabilities.

Today I was looking to use it for filtering data from a 2d array.  I saw in the documentation I can assign such an array through .Items.  However, I don't see now how I can filter a 2d array.  The method arguments don't seem to include the index of the column that I would filter on, and the examples refer to 1d arrays.

Am I correct that currently these methods only support 1d arrays, and if so is there any intention to expand them to 2d arrays?

**Comment by ws-garcia** [comment]
Apparently, there is no options to filter 2D arrays. How ever, you can contribute with this great project or to find an alternative one.

**Comment by Senipah** [comment]
I originally had it recursing through each item in 2d arrays to filter entries individually. Why I took that approach IDK. Seems like filtering 2d arrays by column index is probably more useful. Will add now. Docs to be updated shortly... :)

**Comment by Senipah** [comment]
Change included in v1.8.0. Test coverage included by may require more. Will look at adding further coverage tomorrow/this weekend when I update the docs.

**Comment by mehrlander** [comment]
Great to hear.  Using an index makes sense to me, as long column names aren't available.

I confirmed that I was able to run a basic filter.  I think a question for next steps is whether it could a.) allow for "like" filtering with wildcards or "contains" filtering (the latter in the style of native VBA filter()), and b.) filtering on multiple columns, but that is tricky to manage intuitively, as full functionality presumably required "and" versus "or" chaining.  Presumably that rabbit hole is why Excel has its standard of no more than 2 filter criteria.

Without "like" or "contains" filtering, I suppose one can add a helper column (loop through the array using InStr() or Like on  each element in the desired column to create a new column of booleans) and then filter on the helper column.  That approach can also be used for multiple conditions.  I have not gotten far enough to see whether BetterArray would make that easier.

Apologies if this is the wrong place to put it, but I was also confused by the use of "recurse" and "recursive" in several methods.  I understand recursion as calling a function within itself.  There is a reference to nested arrays, and I could also see how dealing with nested arrays might use recursion (say, to list out all elements in an array and any subarrays, like recursive directory listing functions).  Is that the idea?  Personally I can't imagine working much with nested arrays (I kind of love the "tidy data" concept of one-record = 1 row popularized by "tidyverse" in R), but if I did, my intuition  tells me it would be unlikely that I would want to run the same function across nested levels.  Granted: I may have misunderstood, or I may just be unaware of the use cases, but possibly if it is confusing to me it may be to others as well, FWIW.

**Comment by ws-garcia** [comment]
> I confirmed that I was able to run a basic filter

To achieve this goal, you need a specialized piece of code that provides a source of expression evaluation. Therefore, you can achieve your goal by combining VBA Better Array and the selected expression evaluator.

This way you can filter arrays by multiple columns with a relatively infinite amount of filtering levels/conditions.
