### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ws-garcia** [Senipah/VBA-DynamicArray#2]
I currently work on a CSV-VBA interface that I suposses'll to allow users exchange data between VBA arrays and CSV files, like a method of your project do, but at really high speed. Your code is able to read CSV data, but in my test, *_on a fairly outdated laptop, the performance of it is frustrating_*. Some suggestion?

**Comment by Senipah** [comment]
Yeah performance does suck on my method - I've actually been reworking it for a while on a local branch to address it but haven't pushed any changes here yet.

To be honest, a CSV parser doesn't really belong in my array class - it's not really the core focus of this project. There just didn't really seem to be any good CSV parsing library for VBA available so I just tacked the method on in this class as I had a need for it at the time., 

I do intend to merge the branch I've been working on but I will probably add a deprecation note in the docs for my [FromCSV](https://senipah.github.io/VBA-Better-Array/api/methods/FromCSV.html) method to direct people to your library.

**Comment by ws-garcia** [comment]
Thanks for your reply dear @Senipah. In the next days, I will be releasing a major update for the VBA-CSVinterface project. The update will add to the project the following enhancements:

- Fully compliant with the RFC4180 standard for CSV files.
- At least 70% faster than the solutions provided for VBA Language, with a 2x speed outperform in the worst escenarios.
- Encoding detection for UTF-8, Unicode, and  BigEndian.

All of this without losses the performance philosophy over which the project was built.

**Comment by Senipah** [comment]
Sounds like good features! There is definitely a need for a robust (and 4180 compliant) library to handle this so I'm pleased to hear someone is working on it.

I run the VBA subreddit (https://www.reddit.com/r/vba/) and I'm sure people would be interested in you sharing your work there when you are at a release stage if you wanted to make a post

**Comment by ws-garcia** [comment]
So it will be done. It's nice to be able to have your support for share the work to the open source community. Thanks!

**Comment by Senipah** [comment]
By the way, I notice you use a call to Strings.Split() to break the data into rows

        'Split each line into an array entry
        csvArray() = Split(csvText, LinesDelimiter)

Does this escape a line delimiter escaped in double quotes?

**Comment by ws-garcia** [comment]
This is precisely the enhancement I'm currently testing. The ImportFromCSV method still using `Split() ` function in addition to a couple of tiny `MidB$() ` and `AscW() ` loops.

One of the current testing file, successfully parses by class, contains the following 

```
"Field with 
multiple lines" , "Another field 
with some 
line breaks inside" , "Include some  comma, for test, and some [" "] Quotes" , Normal field here
1, 2, 3 ,4 
"Field 1", "Field 2" , Field 3 , "Field 4" 
```
I'll notify you when the code is already updated. Your replies really matter!

**Comment by ws-garcia** [comment]
Although, I use the classic approach, that's means the parse occurs in lineal way, for futures updates I hope design a new philosophy for allowing parse files in parallel. Obviously this is an idealization that can be useful for migration to modern programming languages, knowing that, in the fact, VBA is a single thread one.

In my lasted tests, running on a `Win 10 x64`, `Excel 2019 x86` and the `Intel Core i7-4500u @1.80-2.40 GHz `, the parse take 4.5 sec. for import a file with 400k records (40.20 MB).

**Comment by Senipah** [comment]
Cool, good luck with it! I only asked because it was the way I find the line endings that was killing the performance of my method. If I were using Split() to separate rows my method would have been much faster (but then wouldn't have been RFC 4180 compliant).

**Comment by Senipah** [comment]
For what it's worth I have now pushed the refactor I had on a local branch (which was something I started back [a while ago](https://github.com/Senipah/VBA-Better-Array/issues/1)).

Still not as performant as yours but faster than it was, I think? Certainly more maintainable, which is all I really care about, lol.

I'd appreciate it if you could update your benchmark scores 😃 

In my testing I get this for yours: 

```
CSVinterface [ImportFromCSV]: 10000 Sales Records.csv
Time taken: 0.0390625
CSVinterface [ImportFromCSV]: 100000 Sales Records.csv
Time taken: 0.421875
CSVinterface [ImportFromCSV]: 1500000 Sales Records.csv
Time taken: 10.39844
```

and these are the times I get for mine (v1.6.0):

```
+----------------------------------+
| Reading: 10000 Sales Records.csv |
+----------------------------------+
10,000 rows parsed
Time taken: 0.28125
+-----------------------------------+
| Reading: 100000 Sales Records.csv |
+-----------------------------------+
100,000 rows parsed
Time taken: 2.867188
+------------------------------------+
| Reading: 1500000 Sales Records.csv |
+------------------------------------+
1,500,000 rows parsed
Time taken: 49.24219
```
---

edit:

Performing the same benchmark on v1.5.2 of my library I get these speeds:

```
+----------------------------------+
| Reading: 10000 Sales Records.csv |
+----------------------------------+
Found 10,001 rows of data
10,001 rows parsed
Time taken: 1.554688
+-----------------------------------+
| Reading: 100000 Sales Records.csv |
+-----------------------------------+
Found 100,001 rows of data
100,001 rows parsed
Time taken: 163.2109
```

so my method is now significantly faster and still RFC 4180 compliant! Grateful you making this thread as otherwise I might never have gotten around to finishing those changes 😄

**Comment by Senipah** [comment]
oh, and I added links to your lib in my docs: https://senipah.github.io/VBA-Better-Array/api/methods/FromCSVFile.html

**Comment by ws-garcia** [comment]
I need to update all my benchmark, in the fact @sdkn104 improved the performance of his methods like you did. Will be a pleasure uptade all about your nice developed project! If you notice, in the previous release I gave you some credits, in the next release @Senipah and @sdkn104 will be on the top of the list!

**Comment by ws-garcia** [comment]
I really appreciate you taking the time to reply me! Is great honor knowing you have the intention of collaborate with me on the `CSVinterface` class. Best regards @Senipah!

**Comment by ws-garcia** [comment]
> 
> 
> For what it's worth I have now pushed the refactor I had on a local branch (which was something I started back [a while ago](https://github.com/Senipah/VBA-Better-Array/issues/1)).
> 
> Still not as performant as yours but faster than it was, I think? Certainly more maintainable, which is all I really care about, lol.
> 
> I'd appreciate it if you could update your benchmark scores 😃
> 
> In my testing I get this for yours:
> 
> ```
> CSVinterface [ImportFromCSV]: 10000 Sales Records.csv
> Time taken: 0.0390625
> CSVinterface [ImportFromCSV]: 100000 Sales Records.csv
> Time taken: 0.421875
> CSVinterface [ImportFromCSV]: 1500000 Sales Records.csv
> Time taken: 10.39844
> ```
> 
> and these are the times I get for mine (v1.6.0):
> 
> ```
> +----------------------------------+
> | Reading: 10000 Sales Records.csv |
> +----------------------------------+
> 10,000 rows parsed
> Time taken: 0.28125
> +-----------------------------------+
> | Reading: 100000 Sales Records.csv |
> +-----------------------------------+
> 100,000 rows parsed
> Time taken: 2.867188
> +------------------------------------+
> | Reading: 1500000 Sales Records.csv |
> +------------------------------------+
> 1,500,000 rows parsed
> Time taken: 49.24219
> ```
> 
> edit:
> 
> Performing the same benchmark on v1.5.2 of my library I get these speeds:
> 
> ```
> +----------------------------------+
> | Reading: 10000 Sales Records.csv |
> +----------------------------------+
> Found 10,001 rows of data
> 10,001 rows parsed
> Time taken: 1.554688
> +-----------------------------------+
> | Reading: 100000 Sales Records.csv |
> +-----------------------------------+
> Found 100,001 rows of data
> 100,001 rows parsed
> Time taken: 163.2109
> ```
> 
> so my method is now significantly faster and still RFC 4180 compliant! Grateful you making this thread as otherwise I might never have gotten around to finishing those changes 😄

The benckmark all ready online within the [CSV interface v1.1.0](https://github.com/ws-garcia/VBA-CSV-interface/releases/tag/v1.1.0) release. See the [documentation repo](https://ws-garcia.github.io/VBA-CSV-interface/). Best regards!

**Comment by Senipah** [comment]
Procedure (Author) | OH | HF | AF | LargeF | LargeFQ
-- | -- | -- | -- | -- | --
ImportFromCSVString(W. García) | 2.4844 | 2.6797 | 2.56250.9531 | 2.9844 | 4.39062.4844
FromCSVString(@Senipah) | 13.5312 | 13.4922 | 14.4453 | 16.0234 | 22.3047
ParseCSVToArray/ADO(@sdkn104) | 3.5000 | 3.7969 | 4.5156 | 7.2812 | 11.7422

Can I see the code you used to generate these figures?

**Comment by ws-garcia** [comment]
Of course yes!

For test the code, I used this for the special syntax CSV files (**OH**, **HF** and **AF**):
```
Sub test()
    Dim csv As CSVinterface, tmpCSV As String
    Dim i As Long, avg As Double,  e As Double, f As Double
    Dim SenipahArray As Variant, filePath As String

    filePath = "[...]\RFC-4180_HF.csv"

    Debug.Print "Parsed file: "; filePath

    Set csv = New CSVinterface
    Set Senipah = New BetterArray
    tmpCSV = csv.GetDataFromCSV(filePath)

    'Test SENIPAH method
    avg = 0
    e = Timer
    For i = 1 To 100000
        Call Senipah.FromCSVString(tmpCSV)
    Next i
    f = Timer
    SenipahArray = Senipah.Items
    avg = avg + CDbl(f - e)
    Debug.Print "[Senipah FromCSVString:"; Round(avg, 4); "seconds]"
    Debug.Print "**************************************************************"
End Sub
```

For bigger files (**LargeF** and **LargeFQ**) I used a simple call to each one procedure.

**Comment by Senipah** [comment]
Thank you! I may take the `Debug.Print Format$(lastRow, "#,###") & " rows parsed"` line out of mine and ask you to run the benchmark again in the future release because if that is printing 100k times it will significantly impact my run time.

It is expected for mine to be a bit slower though as I parse to a jagged variant array so that is plays nicely with the other array methods in my class.

**Comment by ws-garcia** [comment]
In the test, I carefully commented the Debug.Print line of your code. I really thank you for the advice of the bad Encoding file format and the missed Enum. The last of this errors occur because I placed this Enum in a `.bas` module used for test the code. Hope to read your work around for your CSV parser, I still need help to refactoring and improving mine.

**Comment by ws-garcia** [comment]
> It is expected for mine to be a bit slower though as I parse to a jagged variant array so that is plays nicely with the other array methods in my class.

This is a great conclusion. The variant data type is a performance killer. Can you code your parser for output 2D string array?

**Comment by Senipah** [comment]
Appreciate you taking the time to comment out the debug.prints. 

> Can you code your parser for output 2D string array?

The CSV Parser could in isolation, but to integrate with the rest of the BetterArray class it needs to be a jagged Variant array (so that it can be sorted, sliced, etc). The CSV parsing is only really a small side feature of my class, not the "main attraction".

My library is really more about convenience than performance. If performance is paramount then obviously the use of Variant arrays is a no-no but for most day to day tasks it is "good enough". If it isn't, my docs link to your repo 😉 

I will look at mine if comparing bytes() rather than string characters can add any performance to mine but for my purposes I consider the performance I currently have acceptable. Parsing the csv is still fast relative to some of the other operations (sorting for example - I am currently about to push an option to use TimSort rather than Quicksort for my default sort method).

**Comment by ws-garcia** [comment]
Few months ago I was working on sorting algorithms for big data set over VBA. My work stops when implemented the Dual-Pivot Yaroslavskiy's QuickSort. So, is good to read you'll have your own implementation of one of the most fast and stable sorting algorithms. Please, take a look to the Burstsort for your purpose. 

Don't doubt collaborate in CSV interface project. Best regards dear @Senipah!

**Comment by Senipah** [comment]
Yeah [quicksort ](https://senipah.github.io/VBA-Better-Array/api/methods/Sort.html) is the algo my sort method has used from the beginning. The problem i have found with quicksort, though, is that it quickly runs out of stack frames. This might be something I can tweak in my implementation, perhaps by setting a recursion limit, but regardless I am in the final stages of testing my Timsort implementation and making that the default.

I will still include quicksort as an option, it's just that Timsort will be the default. I will include [Introsort ](https://en.wikipedia.org/wiki/Introsort) too.

I will look into burstsort but it looks like this is only really suitable for strings? I need a general purpose sorting algorithm.

>Don't doubt collaborate in CSV interface project. Best regards dear @Senipah!

Will do!

**Comment by ws-garcia** [comment]
> I will look into burstsort but it looks like this is only really suitable for strings? I need a general purpose sorting algorithm.

The core idea I still thinking is use BurstSort algorithm when the desired sorting column holds strings values. This can be done with a simple `IsNumeric` function call.

> Will do!

Thaks for that.

**Comment by Senipah** [comment]
> This can be done with a simple IsNumeric function call.

Just because an element isn't a number doesn't make it a string - my array could contain objects, arrays, custom types etc. I do have a way of discerning this but in any case it is an O(n) operation to check if all elements are strings so no benefit to be gained here by using burstsort if thats something I need to check before hand.. It's just not a good fit for my class. might be beneficial to you though as you are only working with strings

**Comment by ws-garcia** [comment]
> > This can be done with a simple IsNumeric function call.
> 
>my array could contain objects, arrays, custom types etc.

Understood, I was out of focus that point about your array manager project.
