### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fshhady** [Senipah/VBA-DynamicArray#26]
**Describe the bug**
if get array from range the Includes() function is not seem to work.

**To Reproduce**
Public Sub Test()
    Dim arrBA As New BetterArray
    '----------------------
    arrBA.FromExcelRange Sheet1.Range("G1:I4")
    Debug.Print arrBA.Includes(3)
End Sub

**Expected behavior**
exprected result is true if the range contains the value 3, but the result is always false.

**Screenshots**
![image](https://github.com/user-attachments/assets/ed507a3e-49ec-46d5-990e-b56c3c4b6708)

**Operating System:**
 - Windows 10

**Host Application:**
 - MS Excel,

**Comment by ws-garcia** [comment]
An eye bird view make me think that there is an error/typo in your range definition. Actually `Sheet1.Range("G7:I10")` doesn't content the value you are trying to find. Your data range, looking at the image and the provided code, is `Sheet1.Range("G1:I4")`. Fix it for record and wait author response.

Edit:

Given that your array isn't one-dimensional, your code needs to use recursion. 

Try `arrBA.Includes(3, recurse:=True)`

**Comment by fshhady** [comment]
@ws-garcia thanks for your comment.
it worked after using  recurse:=true

**Comment by ws-garcia** [comment]
Please @fshhady, close the issue as completed.
