### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ws-garcia** [Senipah/VBA-DynamicArray#3]
Dear @Senipah,  I still testing the CSV Interface class, and today got the `ImportFromCSV ` and `ImportFromCSVstring ` methods working fine. Trying to use your `FromCSVString` method, over a special syntax CSV file, the returned results are incorrect. 

The procedure used for testing is like the given bellow
```
Sub test()
	Dim WGNEWstrArray() As String, filePath As String, Senipah As BetterArray
	Dim SenipahArray As Variant

	‘Some code here

	Call Senipah.FromCSVString(tmpCSV)
	SenipahArray = Senipah.Items

	‘Some code here
End Sub
```
I let you the used CSV file in addition to an Immediate and Watches windows screenshot.

I’ll wait for your reply to update my benchmarks. Best regards!

**Expected behavior**
The CSV file contains 3 records, each one of which contains 4 fields.

**Screenshots**
![Captura de pantalla (89)](https://user-images.githubusercontent.com/70865364/96664260-60de6180-1320-11eb-84ba-6b59df2f451e.png)

**Operating System:**
 - Windows 10 Pro.

**Host Application:**
 - MS Excel

**CSV file**
[RFC-4180_OH.zip](https://github.com/Senipah/VBA-Better-Array/files/5412803/RFC-4180_OH.zip)

**Comment by Senipah** [comment]
Hey! Thank you so much for letting me know about this!

It was a simple off-by-one error as far as I can tell - the above commit solves the issue by changing:
```
                    j = j + 1
                    cursor = j + 1
```
To:
`                    cursor = j + 2`

**Comment by Senipah** [comment]
I'd be very grateful if you could retest on your end if you find the time (release 1.6.1). Of course, if there are still problems I will happily reopen this issue.

**Comment by Senipah** [comment]
I also just fixed an issue where string in CSV weren't getting unquoted correctly in v1.6.2 just now, so that's the latest release

**Comment by ws-garcia** [comment]
Only a question, before do anything, can your parser handle an variable number of trailing spaces? i.e. A secuence like `Space(2) & "," & Space(1)` or  `Space(4) & ","` and en of a record.

**Comment by Senipah** [comment]
Should do. That's actually part of the reason this bug occurred. These headers sometimes have varying numbers of spaces:

```
"Field with 
multiple lines" ,"Another field 
with some 
line breaks inside" , "Include some  comma, for test, and some [""] Quotes" , "Normal field here" 
```
That whole sample file parses without issue now. 

---

Also worth noting that all strings parsed from the CSV are trimmed in this function, so that ` " some field here " ` is stored as `some field here`:

```
Private Function UnquoteString(ByRef element As String) As String
    Dim localElement As String
    localElement = Trim$(element)
    If Asc(Left$(localElement, 1)) = 34 And Asc(Right$(localElement, 1)) = 34 Then
        'trim string delimiters
        localElement = Mid$(localElement, 2, Len(localElement) - 2)
    End If
    UnquoteString = Trim$(localElement)
End Function
```

**Comment by Senipah** [comment]
Just tested this as a CSV:

```
"Field with 
multiple lines" ,"Another field 
with some 
line breaks inside   "    , "Include some  comma, for test, and some [""] Quotes" , "Normal field here" 
1, 2,    3    ,4 
            Field 1,            Field 2                ,               Field 3 , Field 4
```

and I get this as the output:

| Field   with             multiple lines | Another field             with some             line breaks inside | Include some    comma, for test, and some [""] Quotes | Normal field here |
|-----------------------------------------|--------------------------------------------------------------------|-------------------------------------------------------|-------------------|
| 1                                       | 2                                                                  | 3                                                     | 4                 |
| Field 1                                 | Field 2                                                            | Field 3                                               | Field 4           |

So yes is the answer

**Comment by ws-garcia** [comment]
Thanks for your answer! I have successfully updated benchmark on a local branch. In the next few days I'll put in online and alert to you. So, delayed by an unexpected errors fixes, I hope the code be available to the community very soon. 😎
