### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ws-garcia** [Senipah/VBA-DynamicArray#4]
Dear @Senipah , in the last stage of testing for the CSV interface I found a little bug in the method `FromCSVString` of the VBA Better Array class. Specifically, I was trying to make my project able to handle empty CSV files and records having zero length fields inside them. More details: the error occurs over the `UnquoteString` function (line 2450). See the attached screenshot

**To Reproduce**
The test string is the following:
```vb
"",[vbCrLf]
,"" [vbCrLf]
Field1,Field2[vbCrLf]
```
**Screenshot**
![Captura de pantalla (106)](https://user-images.githubusercontent.com/70865364/97651713-3c2a6e00-1a33-11eb-86aa-7c143d5fba96.png)

**Operating System:**
 - Windows 10 Pro

**Host Application:**
 - MS Excel 32 bits

**Comment by Senipah** [comment]
Thanks for the heads-up. closed in 5168a06 (included in release 1.6.4).

Cheers
