### ISSUE TITLE
Docs mistake

### ISSUE THREAD

**Issue by ws-garcia** [Senipah/VBA-DynamicArray#5]
**Is your feature request related to a problem?**  

NO

**Describe the solution you'd like**

There is a little mistake in the ToCSVFile method description.

>The ToCSVFile() returns an RFC 4180 compliant string representation of the stored array.
>
>It is the same as **ToCSVFile**() but accepts an output path to which the CSV data will be written.

Maybe you mean **ToCSVString**

**Comment by Senipah** [comment]
Yup, good spot :)

Thanks 👍
