### ISSUE TITLE
can betterarray sort descending?

### ISSUE THREAD

**Issue by winner106** [Senipah/VBA-DynamicArray#9]
can betterarray sort descending?
First use betterarray.sort， then use betterarray.Reverse

am i right？ Thank you again.

**Comment by Senipah** [comment]
Hi @winner106 

Yeah I may look at adding descending - would be easy enough to add, but the reason I don't at the moment is that `.Reverse()` is a fairly cheap operation to perform, so there would not be much to be gained in performance from sorting in descending in the first place vs sorting ascending and then reversing.

edit: by the way, `sort` and `reverse` are both chainable. So you can write it in one line as `BetterArray.Sort().Reverse()`

**Comment by winner106** [comment]
Cool,Thank you for your guidance
